name: peco-tsb
version: '0.5.1-1'
summary: Simplistic interactive filtering tool
description: |
  peco can be a great tool to filter stuff like logs, process stats, find
  files, because unlike grep, you can type as you think and look through the
  current results.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  peco:
    command: peco

parts:
  peco:
    source: .
    source-type: git
    plugin: make
    make-parameters: ["release-linux-amd64"]
    artifacts:
      - releases/peco_linux_amd64/Changes
      - releases/peco_linux_amd64/README.md
      - releases/peco_linux_amd64/peco
